// Generated by CoffeeScript 1.6.3
(function() {
  var CM, Content;

  CM = (function() {
    function CM() {
      this.content = [];
    }

    CM.prototype.loadContent = function(cb) {
      var _this = this;
      console.log('loading content');
      return $.get("/content.json", function(data) {
        var content, _i, _len, _ref;
        console.log('data', data);
        _this._rawContent = data;
        _ref = _this._rawContent;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          content = _ref[_i];
          _this.content.push(new Content(content));
        }
        if (cb) {
          return cb();
        }
      });
    };

    return CM;

  })();

  Content = (function() {
    function Content(content) {
      this.content = content;
    }

    Content.prototype.getHtml = function(cb) {
      var htmlUrl;
      htmlUrl = this.content.uri.replace(".json", ".html");
      return $.get(htmlUrl, function(data) {
        if (cb) {
          return cb(data);
        }
      }).fail(function(xhr, data, string) {
        console.log(data);
        return console.log(string);
      });
    };

    Content.prototype.getCard = function(cb) {
      var cardUrl;
      cardUrl = this.content.uri.replace(".json", ".card");
      return $.get(cardUrl, function(data) {
        if (cb) {
          return cb(data);
        }
      });
    };

    Content.prototype.getJSON = function() {
      return $.get(this.content.uri, function(data) {
        if (cb) {
          return cb(data);
        }
      });
    };

    Content.prototype.toJSON = function() {
      return this.content;
    };

    return Content;

  })();

  (function() {
    CM = new CM();
    return CM.loadContent(function() {
      var article, _i, _len, _ref, _results,
        _this = this;
      $("title").text = "Welcome to My Site";
      _ref = CM.content;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        article = _ref[_i];
        _results.push((function(article) {
          return article.getHtml(function(html) {
            $(".content").append($(html));
            return $(".nav").append($("<a href=\"" + article.content.link + "\">" + article.content.content.title.content.text + "</a>"));
          });
        })(article));
      }
      return _results;
    });
  })();

}).call(this);
